USE [master]
GO
/****** Object:  Database [TFT.Test]    Script Date: 8.2.2023. 11:32:05 ******/
CREATE DATABASE [TFT.Test]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TFT.Test', FILENAME = N'{Solution root folder}\TFT.Repository\DataSource\UnitTest\TFT.Test.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TFT.Test_log', FILENAME = N'{Solution root folder}\TFT.Repository\DataSource\UnitTest\TFT.Test_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [TFT.Test] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TFT.Test].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TFT.Test] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TFT.Test] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TFT.Test] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TFT.Test] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TFT.Test] SET ARITHABORT OFF 
GO
ALTER DATABASE [TFT.Test] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TFT.Test] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TFT.Test] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TFT.Test] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TFT.Test] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TFT.Test] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TFT.Test] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TFT.Test] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TFT.Test] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TFT.Test] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TFT.Test] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TFT.Test] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TFT.Test] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TFT.Test] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TFT.Test] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TFT.Test] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TFT.Test] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TFT.Test] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TFT.Test] SET  MULTI_USER 
GO
ALTER DATABASE [TFT.Test] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TFT.Test] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TFT.Test] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TFT.Test] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TFT.Test] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TFT.Test] SET QUERY_STORE = OFF
GO
USE [TFT.Test]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [TFT.Test]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 8.2.2023. 11:32:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ActorAgreements]    Script Date: 8.2.2023. 11:32:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ActorAgreements](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[IsInvited] [bit] NOT NULL,
	[IsAccepted] [nvarchar](max) NOT NULL,
	[Honorarium] [decimal](18, 0) NOT NULL,
	[MovieID] [bigint] NOT NULL,
	[ActorID] [bigint] NOT NULL,
 CONSTRAINT [PK_ActorAgreements] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Actors]    Script Date: 8.2.2023. 11:32:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Actors](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ActorID] [nvarchar](max) NOT NULL,
	[Username] [nvarchar](max) NOT NULL,
	[Hash] [nvarchar](max) NOT NULL,
	[Salt] [nvarchar](max) NOT NULL,
	[Firstname] [nvarchar](max) NOT NULL,
	[Lastname] [nvarchar](max) NOT NULL,
	[Role] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Actors] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Directors]    Script Date: 8.2.2023. 11:32:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Directors](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DirectorID] [nvarchar](max) NOT NULL,
	[Username] [nvarchar](max) NOT NULL,
	[Hash] [nvarchar](max) NOT NULL,
	[Salt] [nvarchar](max) NOT NULL,
	[Firstname] [nvarchar](max) NOT NULL,
	[Lastname] [nvarchar](max) NOT NULL,
	[Role] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Directors] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GenreMovie]    Script Date: 8.2.2023. 11:32:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GenreMovie](
	[Genres_ID] [bigint] NOT NULL,
	[Movies_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_GenreMovie] PRIMARY KEY CLUSTERED 
(
	[Genres_ID] ASC,
	[Movies_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Genres]    Script Date: 8.2.2023. 11:32:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Genres](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Genres] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Movies]    Script Date: 8.2.2023. 11:32:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Movies](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](max) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[Duration] [datetimeoffset](7) NOT NULL,
	[StartProduction] [datetime] NOT NULL,
	[EndProduction] [datetime] NOT NULL,
	[Budget] [decimal](18, 0) NOT NULL,
	[DirectorID] [bigint] NOT NULL,
 CONSTRAINT [PK_Movies] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 8.2.2023. 11:32:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](max) NOT NULL,
	[Hash] [nvarchar](max) NOT NULL,
	[Salt] [nvarchar](max) NOT NULL,
	[Firstname] [nvarchar](max) NOT NULL,
	[Lastname] [nvarchar](max) NOT NULL,
	[Role] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_FK_ActorActorAgreement]    Script Date: 8.2.2023. 11:32:06 ******/
CREATE NONCLUSTERED INDEX [IX_FK_ActorActorAgreement] ON [dbo].[ActorAgreements]
(
	[ActorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_FK_ActorAgreementMovie]    Script Date: 8.2.2023. 11:32:06 ******/
CREATE NONCLUSTERED INDEX [IX_FK_ActorAgreementMovie] ON [dbo].[ActorAgreements]
(
	[MovieID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_FK_GenreMovie_Movie]    Script Date: 8.2.2023. 11:32:06 ******/
CREATE NONCLUSTERED INDEX [IX_FK_GenreMovie_Movie] ON [dbo].[GenreMovie]
(
	[Movies_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_FK_MovieDirector]    Script Date: 8.2.2023. 11:32:06 ******/
CREATE NONCLUSTERED INDEX [IX_FK_MovieDirector] ON [dbo].[Movies]
(
	[DirectorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ActorAgreements]  WITH CHECK ADD  CONSTRAINT [FK_ActorActorAgreement] FOREIGN KEY([ActorID])
REFERENCES [dbo].[Actors] ([ID])
GO
ALTER TABLE [dbo].[ActorAgreements] CHECK CONSTRAINT [FK_ActorActorAgreement]
GO
ALTER TABLE [dbo].[ActorAgreements]  WITH CHECK ADD  CONSTRAINT [FK_ActorAgreementMovie] FOREIGN KEY([MovieID])
REFERENCES [dbo].[Movies] ([ID])
GO
ALTER TABLE [dbo].[ActorAgreements] CHECK CONSTRAINT [FK_ActorAgreementMovie]
GO
ALTER TABLE [dbo].[GenreMovie]  WITH CHECK ADD  CONSTRAINT [FK_GenreMovie_Genre] FOREIGN KEY([Genres_ID])
REFERENCES [dbo].[Genres] ([ID])
GO
ALTER TABLE [dbo].[GenreMovie] CHECK CONSTRAINT [FK_GenreMovie_Genre]
GO
ALTER TABLE [dbo].[GenreMovie]  WITH CHECK ADD  CONSTRAINT [FK_GenreMovie_Movie] FOREIGN KEY([Movies_ID])
REFERENCES [dbo].[Movies] ([ID])
GO
ALTER TABLE [dbo].[GenreMovie] CHECK CONSTRAINT [FK_GenreMovie_Movie]
GO
ALTER TABLE [dbo].[Movies]  WITH CHECK ADD  CONSTRAINT [FK_MovieDirector] FOREIGN KEY([DirectorID])
REFERENCES [dbo].[Directors] ([ID])
GO
ALTER TABLE [dbo].[Movies] CHECK CONSTRAINT [FK_MovieDirector]
GO
USE [master]
GO
ALTER DATABASE [TFT.Test] SET  READ_WRITE 
GO
